# First, open a file handle

filename = "validfile.txt"  
file_handle1 = openfile(filename, True)  


# open the same file again
try:
    file_handle2 = openfile(filename, True)  
    log("Fail: FileInUseError Expected")  # Log if no exception
except FileInUseError as e:
    pass
except Exception as e:
    log("Unexpected Error")  # Log any unexpected errors

